# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
  # activer la désérialization automatique du contenu de la requette
  body_converter:
        enabled: true
        validate: true
        validation_errors_argument: violations
  # les formats que nous souhaitons pouvoir gérer pour la sérialization
  view:
    view_response_listener: 'force'
    formats: { json: true, xml: false, rss: false }
    
  # prendre en considération les champs null lors de la sérialisation
  serializer:
    serialize_null: true
    
  format_listener:
    rules:
      - { path: '^/', prefer_extension: true, fallback_format: 'json', priorities: ['json'] }
  param_fetcher_listener: force
  exception:
      enabled: true
      exception_controller: 'fos_rest.exception.controller:showAction'
      codes:
        App\Exception\ResourceValidationException: 400
        App\Exception\EntityNotFoundException: 404
        # \LogicException: 400
        # \DomainException: 400
      messages:
        App\Exception\ResourceValidationException: true
        App\Exception\EntityNotFoundException: true
        # Doctrine\ORM\EntityNotFoundException: true
        # \LogicException: true
        # \DomainException: true
#    param_fetcher_listener:  true
#    allowed_methods_listener:  true
#    routing_loader: true
#    view:
#        view_response_listener:  true
#    exception:
#        codes:
#            App\Exception\MyException: 403
#        messages:
#            App\Exception\MyException: Forbidden area.
#    format_listener:
#        rules:
#            - { path: ^/api, prefer_extension: true, fallback_format: json, priorities: [ json, html ] }
