#index:
#    path: /
#    controller: App\Controller\DefaultController::index
api_login_check:
    path: /login_check
register:
    path: /customers
    controller: App\Controller\CustomerController::register
    methods: POST
gesdinet_jwt_refresh_token:
    path: /token/refresh
    controller: gesdinet.jwtrefreshtoken::refresh
