#index:
#    path: /
#    controller: App\Controller\DefaultController::index
api_login_check:
    path: /login_check
    methods: POST  
register:
    path: /customers
    controller: App\Controller\CustomerController::register
    methods: POST
gesdinet_jwt_refresh_token:
    path: /token/refresh
    methods: POST
    controller: gesdinet.jwtrefreshtoken::refresh
app.swagger_ui:
    path: api/doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }
